name: Windows (x64) Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  BUILD_OPTION: "x64"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019 # Set temporary until link error is found
    #windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      # Build your program with the given configuration
      run: scripts/github/build_xtd_and_launch_unit_tests_on_windows.bat
      
